title: "Secrets of Strixhaven - Set Analysis"
description: "MTG Secrets of Strixhaven (SOS) analysis for Limited/Draft"
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: auto
